<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 */

$partial = $this->plugin('partial');
?>

<div class="comments-list">
    <?php foreach ($comments as $comment): ?>
    <div id="comment-<?= $comment->id() ?>" class="comment" data-comment-id="<?= $comment->id() ?>">
        <?= $partial('common/comment-single', ['comment' => $comment]) ?>
    </div>
    <?php endforeach; ?>
</div>
