<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var int $parent_id
 */

$partial = $this->plugin('partial');
?>

<div class="comments-thread">
<?php foreach ($comments as $comment) : ?>
    <?php $parent = $comment->parent(); ?>
    <?php if (($parent && $parent->id() == $parent_id) || (empty($parent) && empty($parent_id))): ?>
    <div id="comment-<?= $comment->id() ?>" class="comment">
        <?= $partial('common/comment-single', ['comment' => $comment]) ?>
        <div class="comment-children">
            <?= $partial('common/comments-thread', ['comments' => $comments, 'parent_id' => $comment->id()]) ?>
        </div>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>