<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var string $label
 * @var string $structure "flat" (default) or "threaded". "threaded" here.
 * @var bool $closedOnLoad
 * @var int $maxLength
 * @var bool $skipGravatar
 * @var string $legalText
 * @var int|null $parentId
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');

$vars = $this->vars();
?>

<div class="resource-comments comments-thread">
<?php foreach ($comments as $comment):
    $parent = $comment->parent();
    if (($parent && $parent->id() === $parentId) || (empty($parent) && empty($parentId))):
        $vars->offsetSet('comment', $comment);
        $vars->offsetSet('parentId', $comment->id());
        ?>
    <div id="comment-<?= $comment->id() ?>" class="comment" data-comment-id="<?= $comment->id() ?>">
        <?= $partial('common/comment-single') ?>
        <div class="comment-children">
            <?= $partial('common/comments-thread') ?>
        </div>
    </div>
    <?php endif; ?>
<?php endforeach; ?>
</div>
