<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var string $label
 * @var string $structure "flat" (default) or "threaded"
 * @var bool $closedOnLoad
 * @var int $maxDepth
 * @var bool $skipGravatar
 * @var string $legalText
 * @var null $parentId For threaded structure only. Null here.
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($assetUrl('css/comment.css', 'Comment'));
$this->headScript()
    ->appendFile($assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/comment.js', 'Comment'), 'text/javascript', ['defer' => 'defer']);

$user = $this->identity();

// Required to manage the base path.
$baseUrl = $site ? $url('site/comment', ['site-slug' => $site->slug()]) : $url('admin/comment');
?>

<details class="comments comments-details" <?= empty($closedOnLoad) ? 'open="open"' : '' ?>>
    <summary class="selection-summary" aria-expanded="<?= empty($closedOnLoad) ? 'true' : 'false' ?>">
        <?= $label ?: $translate('Comments') ?>
    </summary>
    <div id="comments" class="comments-resource" data-comment-url="<?= $escapeAttr($baseUrl) ?>">
        <?php if (empty($comments) && $user): ?>
            <p><?= $translate('No comment yet! Be the first to add one!') ?></p>
        <?php elseif (empty($comments)): ?>
            <p><?= $translate('No comment yet! Log in and be the first to add one!') ?></p>
        <?php elseif (($structure ?? null) === 'threaded'): ?>
            <?= $partial('common/comments-thread') ?>
        <?php else: ?>
            <?= $partial('common/comments-list') ?>
        <?php endif; ?>
    </div>
</details>
