<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var bool $threaded
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$setting = $plugins->get('setting');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$threaded ??= (bool) $setting('comment_threaded');

$this->headLink()
    ->appendStylesheet($assetUrl('css/comment.css', 'Comment'));
$this->headScript()
    ->appendFile($assetUrl('js/comment.js', 'Comment'), 'text/javascript', ['defer' => 'defer']);

// Required to manage the base path.
$addUrl = $url('site/comment', ['action' => 'add'], true);
?>

<div id="comments" class="comments" data-comment-url="<?= $addUrl ?>">
    <?php if ($label = $setting('comment_comments_label')): ?>
    <h2><?= $translate($label) ?></h2>
    <?php endif; ?>
    <?php if (empty($comments)): ?>
    <p><?= $translate('No comment yet! Be the first to add one!') ?></p>
    <?php elseif ($threaded): ?>
        <?= $partial('common/comments-thread', ['comments' => $comments, 'parentId' => null]) ?>
    <?php else: ?>
        <?= $partial('common/comments-list', ['comments' => $comments]) ?>
    <?php endif; ?>
</div>
