<?php $escape = $this->plugin('escapeHtml'); ?>
<div class='comment-author'>
    <?php
    if ($name = $comment->name()):
        if ($website = $comment->website()):
            $authorText = $this->hyperlink($name, $website);
        else:
            $authorText = $name;
        endif;
    else:
        $authorText = $escape($this->translate('Anonymous'));
    endif;
    ?>
    <p class='comment-author-name'><?php echo $authorText; ?></p>
    <?php
        $hash = md5(strtolower(trim($comment->email())));
        $url = "//www.gravatar.com/avatar/$hash";
    ?>
    <img class='gravatar' src="<?php echo $url; ?>" />
</div>
<div class="comment-body<?php if ($flagged = $comment->isFlagged()): ?> comment-flagged<?php endif; ?><?php if ($isSpam = $comment->isSpam()): ?> comment-spam<?php endif; ?>">
    <?php echo $escape($comment->body()); ?>
</div>
<?php if ($this->userIsAllowed(\Comment\Controller\Site\CommentController::class, 'flag')): ?>
<p class="comment-flag"<?php if ($flagged): ?> style="display:none;"<?php endif;?>><?php echo $escape($this->translate('Flag inappropriate')); ?></p>
<?php endif; ?>
<?php if ($this->userIsAllowed(\Comment\Controller\Site\CommentController::class, 'unflag')): ?>
<p class="comment-unflag"<?php if (!$flagged): ?> style="display:none;"<?php endif;?>><?php echo $escape($this->translate('Unflag inappropriate')); ?></p>
<?php endif; ?>
<?php if ($comment->userIsAllowed('create')): ?>
<p class='comment-reply'><?php echo $escape($this->translate('Reply')); ?></p>
<?php endif; ?>
