<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Form\CommentForm $commentForm
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var string $label
 * @var string $structure "flat" (default) or "threaded"
 * @var bool $closedOnLoad
 * @var int $maxLength
 * @var bool $skipGravatar
 * @var string $legalText
 * @var null $parentId For threaded structure only.
 */

$plugins = $this->getHelperPluginManager();
$formText = $plugins->get('formText');
$formLabel = $plugins->get('formLabel');
$formHidden = $plugins->get('formHidden');
$formElement = $plugins->get('formElement');

$user = $this->identity();
$isAnonymous = empty($user);

$commentForm->prepare();
?>

<div id="comment-main-container" data-is-anonymous="<?= (int) $isAnonymous ?>">
    <?php // echo $this->form($commentForm) ?>
    <?php // TODO Add messages only if not set by layout. Anyway, they are available via json. ?>
    <?php if (false && $messages = $this->messages()): ?>
    <div id="comments-flash"><?= $messages ?></div>
    <?php endif; ?>

    <?= $this->form()->openTag($commentForm) ?>

<?php if ($isAnonymous): ?>
    <?php $element = $commentForm->get('o:name'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs">
            <?= $formText($element) ?>
        </div>
    </div>
    <?php $element = $commentForm->get('o:email'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs required">
            <?= $formText($element) ?>
        </div>
    </div>
    <?php $element = $commentForm->get('o:website'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs">
            <?= $formText($element) ?>
        </div>
    </div>
<?php endif; ?>

    <?php $element = $commentForm->get('o:body'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs required">
            <?= $this->formTextArea($element) ?>
        </div>
    </div>

<?php if ($isAnonymous): ?>
    <?php if ($commentForm->has('g-recaptcha-response')): ?>
    <?php $element = $commentForm->get('g-recaptcha-response'); ?>
    <div class="field">
        <div class="inputs required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($commentForm->has('o:check')): /* honeyspot */ ?>
    <?php $element = $commentForm->get('o:check'); ?>
    <div class="field">
        <div class="inputs required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($commentForm->has('address')): /* quick anti-robot */ ?>
    <?php $element = $commentForm->get('address'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php $element = $commentForm->get('address_a'); ?>
    <?= $formHidden($element) ?>
    <?php $element = $commentForm->get('address_b'); ?>
    <?= $formHidden($element) ?>
    <?php endif; ?>
    <?php if ($commentForm->has('legal_agreement')): ?>
    <?php $element = $commentForm->get('legal_agreement'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs required">
            <?= $this->setting('comment_legal_text') ?>
            <?= $this->formCheckbox($element) ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>

    <?= $formHidden($commentForm->get('resource_id')) ?>
    <?= $formHidden($commentForm->get('comment_parent_id')) ?>
    <?= $formHidden($commentForm->get('path')) ?>
    <?= $formHidden($commentForm->get('csrf_' . $resource->id())) ?>
    <?= $formHidden($commentForm->get('csrf')) ?>
    <?php $element = $commentForm->get('submit'); ?>
    <div class="field">
        <div class="field-meta">
        </div>
        <div class="inputs required">
            <?= $this->formElement($element) ?>
        </div>
    </div>
    <?php //echo $this->formButton()->openTag($element) ?>
    <?php //echo $formLabel($element) ?>
    <?php //echo $this->formButton()->closeTag() ?>
    <?= $this->form()->closeTag() ?>
</div>
