<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Comment\Api\Representation\CommentRepresentation $comment
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var string $label
 * @var string $structure "flat" (default) or "threaded".
 * @var bool $closedOnLoad
 * @var int $maxDepth
 * @var bool $skipGravatar
 * @var string $legalText
 * @var int|null $parentId
 */

$plugins = $this->getHelperPluginManager();
$i18n = $plugins->get('i18n');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$userIsAllowed = $plugins->get('userIsAllowed');

if ($name = $comment->name()) {
    $website = $comment->website();
    $authorText = $website ? $hyperlink($name, $website) : $name;
} else {
    $authorText = $escape($translate('Anonymous'));
}

$skipGravatar = (bool) $siteSetting('comment_skip_gravatar');

$publicRequireModeration = $setting('comment_public_require_moderation');
$userrRequireModeration = $setting('comment_user_require_moderation');
$userCanComment = $comment->userIsAllowed('create');
$userCanEdit = $comment->userIsAllowed('edit');
$userCanFlag = $userIsAllowed(\Comment\Controller\Site\CommentController::class, 'flag');
$userCanUnflag = $userIsAllowed(\Comment\Controller\Site\CommentController::class, 'unflag');
?>
<?php /*// The comment id is in comment-list or comments-thread. Comment-thread includes comment children.
<div id="comment-<?= $comment->id() ?>" class="comment" data-comment-id="<?= $comment->id() ?>">
*/ ?>

<div class="comment-header">
    <div class="comment-author">
        <p class="comment-author-name"><?= $authorText ?></p>
        <?php if (empty($skipGravatar)): ?>
        <img loading="lazy" class="gravatar" src="//www.gravatar.com/avatar/<?= hash('sha256', trim($comment->email())) ?>"/>
        <?php endif; ?>
    </div>
    <p class="comment-date"><?= $i18n->dateFormat($comment->created()) ?></p>
</div>

<div class="comment-body<?php if ($flagged = $comment->isFlagged()): ?> comment-flagged<?php endif; ?><?php if ($comment->isSpam()): ?> comment-spam<?php endif; ?>">
    <?= $escape($comment->body()) ?>
</div>

<div class="comment-footer">
    <?php // Don't display the flag when the comments are moderated a priori. ?>
    <?php if (!$publicRequireModeration || !$userrRequireModeration): ?>
    <div class="comment-actions">
        <?php if ($userCanFlag): ?>
        <button type="button" class="comment-action comment-flag"
            <?= $flagged ? ' style="display:none;"' : '' ?>
            aria-label="<?= $v = $escapeAttr($translate('Flag inappropriate')) ?>"
            title="<?= $v ?>">
                <span class="comment-flag-icon"></span>
                <span class="comment-flag-text"><?= $escape($translate('Flag inappropriate')) ?></span>
            </button>
        <?php endif; ?>
        <?php if ($userCanUnflag): ?>
        <button type="button"
            class="comment-action comment-unflag"
            <?= $flagged ? '' : ' style="display:none;"' ?>
            aria-label="<?= $v = $escapeAttr($translate('Unflag inappropriate')) ?>"
            title="<?= $v ?>">
                <span class="comment-flag-icon"></span>
                <span class="comment-flag-text"><?= $escape($translate('Unflag inappropriate')) ?></span>
            </button>
        <?php endif; ?>
        <?php if ($userCanEdit): ?>
        <button type="button"
            class="comment-action comment-edit"
            aria-label="<?= $v = $escapeAttr($translate('Edit')) ?>"
            title="<?= $v ?>">
                <span class="comment-edit-icon"></span>
                <span class="comment-edit-text"><?= $escape($translate('Edit')) ?></span>
            </button>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <?php if ($userCanComment): ?>
    <div class="comment-reply">
        <button type="button"
            class="comment-action comment-reply"
            aria-label="<?= $v = $escapeAttr($translate('Reply')) ?>"
            title="<?= $v ?>">
                <span class="comment-reply-icon"></span>
                <span class="comment-reply-text"><?= $escape($translate('Reply')) ?></span>
            </button>
    </div>
    <?php endif; ?>
</div>

<?php /*
</div>
*/ ?>
