<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var bool $showForm
 * @var bool $showList
 * @var string $label
 * @var string $structure "flat" (default) or "threaded"
 * @var bool $closedOnLoad
 * @var int $maxDepth
 * @var bool $skipGravatar
 * @var string $legalText
 * @var null $parentId For threaded structure only. Null here.
 * @var array $options Options above as an array.
 */

if (empty($showForm) && empty($showList)) {
    return;
}
?>

<div id="comments-container" class="comments-container">
    <?php if ($showList): ?>
    <?= $this->comments($resource, $options ?? []) ?>
    <?php endif; ?>
    <?php if ($showForm): ?>
    <?= $this->commentForm($resource, $options ?? []) ?>
    <?php endif; ?>
</div>
