<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation $comment
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$siteSetting = $plugins->get('siteSetting');
$userIsAllowed = $plugins->get('userIsAllowed');

$skipGravatar = (bool) $siteSetting('comment_skip_gravatar');
?>

<div class="comment-author">
    <?php
    if ($owner = $comment->owner()):
        $authorText = $hyperlink($owner->email(), $url('admin/id', ['controller' => 'user', 'id' => $owner->id()]));
        $authorText .= ' (' . $owner->name() . ')';
    else:
        $authorText = $hyperlink($comment->email(), 'mailto:' . $comment->email());
        if ($comment->name()):
            $authorText .= ' (' . $comment->name() . ')';
        endif;
    endif;
    if ($website = $comment->website()):
        $authorText .= sprintf($translate('Website: %s'), $hyperlink($website, $website));
    endif;
    ?>
    <p class="comment-author-name"><?= $authorText ?></p>
    <?php if (!$skipGravatar): ?>
    <img loading="lazy" class="gravatar" src="'//www.gravatar.com/avatar/<?= hash('sha256', trim($comment->email())) ?>"/>
    <?php endif; ?>
</div>
<div class="comment-actions">
    <ul class="actions">
        <?php // TODO Use buttons instead of a. ?>
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'approve')): ?>
        <li><a href="#"
            class="toggle-property approved unapproved o-icon-<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
            data-url="<?= $escape($comment->url('toggle-approved')) ?>"
            data-status="<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
            aria-label="<?= $escape($translate('Toggle approbation')) ?>"
            title="<?= $escape($translate('Toggle approbation')) ?>"></a></li>
        <?php endif; ?>
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'flag')
            || ($comment->isFlagged() && $userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'unflag'))):
        ?>
        <li><a href="#"
            class="toggle-property flagged unflagged o-icon-<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
            data-url="<?= $escape($comment->url('toggle-flagged')) ?>"
            data-status="<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
            aria-label="<?= $escape($translate('Toggle flag')) ?>"
            title="<?= $escape($translate('Toggle flag')) ?>"></a></li>
        <?php endif; ?>
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'set-spam')
            || $userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'set-not-spam')):
        ?>
        <li><a href="#"
            class="toggle-property spam not-spam o-icon-<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
            data-url="<?= $escape($comment->url('toggle-spam')) ?>"
            data-status="<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
            aria-label="<?= $escape($translate('Toggle spam')) ?>"
            title="<?= $escape($translate('Toggle spam')) ?>"></a></li>
        <?php endif; ?>
        <?php /* // TODO Delete comments from resources.
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'delete')): ?>
        <li><a href="<?= $escape($comment->url('delete')) ?>"
            onclick="return confirm(<?= json_encode($translate('Are you sure to delete this comment?')) ?>;"
            class="o-icon-delete sidebar-content"
            data-sidebar-content-url="<?= $escape($comment->url('delete-confirm')) ?>"
            aria-label="<?= $escape($translate('Delete')) ?>"
            title="<?= $escape($translate('Delete')) ?>"></a></li>
        <?php endif; ?>
        */ ?>
    </ul>
</div>
<div class="comment-body">
    <?= $escape($comment->body()) ?>
</div>
<?php if ($comment->userIsAllowed('create')): ?>
<p class="comment-reply"><?= $escape($translate('Reply')) ?></p>
<?php endif; ?>
