<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation $resource
 * @var int $totalComments
 * @var int $totalApproved
 * @var int $totalFlagged
 * @var int $totalSpam
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$resourceName = $resource->getControllerName();
$column = $resourceName === 'user' ? 'owner_id' : 'resource_id';

// TODO Remove this hack to fix a css issue in user view.
$this->headStyle()->appendStyle('.show .property { justify-content: normal; }');
?>

<div class="property">
    <h4><?= $translate('Comments') ?></h4>
    <ul class="comment-stats">
        <li>
            <?= sprintf($translate('Total: %s'),
                $hyperlink($totalComments, $url('admin/comment', [], ['query' => [$column => $resource->id()]]))
            ) ?>
        </li>
        <li>
            <?= sprintf($translate('Approved: %s / Unapproved: %s'),
                $hyperlink($totalApproved, $url('admin/comment', [], ['query' => [$column => $resource->id(), 'approved' => true]])),
                $hyperlink($totalComments - $totalApproved, $url('admin/comment', [], ['query' => [$column => $resource->id(), 'approved' => false]]))
            ) ?>
        </li>
        <li>
            <?= sprintf($translate('Flagged: %s / Unflagged: %s'),
                $hyperlink($totalFlagged, $url('admin/comment', [], ['query' => [$column => $resource->id(), 'flagged' => true]])),
                $hyperlink($totalComments - $totalFlagged, $url('admin/comment', [], ['query' => [$column => $resource->id(), 'flagged' => false]]))
            ) ?>
        </li>
        <li>
            <?= sprintf($translate('Spam: %s / Not spam: %s'),
                $hyperlink($totalSpam, $url('admin/comment', [], ['query' => [$column => $resource->id(), 'spam' => true]])),
                $hyperlink($totalComments - $totalSpam, $url('admin/comment', [], ['query' => [$column => $resource->id(), 'spam' => false]]))
            ) ?>
        </li>
    </ul>
</div>
