<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var string $label
 * @var string $structure "flat" (default) or "threaded"
 * @var bool $closedOnLoad
 * @var int $maxLength
 * @var bool $skipGravatar
 * @var string $legalText
 * @var null $parentId For threaded structure only. Null here.
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$partial = $plugins->get('partial');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$subscriptionButton = $plugins->get('commentSubscriptionButton');

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($assetUrl('css/comment-admin.css', 'Comment'))
    ->appendStylesheet($assetUrl('css/comment.css', 'Comment'));
$this->headScript()
    ->appendFile($assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/comment-admin.js', 'Comment'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/comment.js', 'Comment'), 'text/javascript', ['defer' => 'defer']);

// Required to manage the base path.
$baseUrl = $url('admin/comment');

// In admin, the label is in the tab.
?>

<div id="comments" class="comments" data-comment-url="<?= $escapeAttr($baseUrl) ?>">
    <?= $subscriptionButton($resource) ?>
    <?php if (empty($comments)): ?>
        <p><?= $translate('No comment yet! Be the first to add one!') ?></p>
    <?php elseif (($structure ?? null) === 'threaded'): ?>
        <?= $partial('common/comments-thread') ?>
    <?php else: ?>
        <?= $partial('common/comments-list') ?>
    <?php endif; ?>
</div>
