<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Comment\Api\Representation\CommentRepresentation $comment
 * @var \Omeka\Api\Representation\AbstractResourceRepresentation $resource
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var string $label
 * @var string $structure "flat" (default) or "threaded"
 * @var bool $closedOnLoad
 * @var int $maxLength
 * @var bool $skipGravatar
 * @var string $legalText
 * @var null $parentId For threaded structure only. Null here.
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$userIsAllowed = $plugins->get('userIsAllowed');

if ($owner = $comment->owner()) {
    $authorText = $hyperlink($owner->email(), $url('admin/id', ['controller' => 'user', 'id' => $owner->id()]));
    $authorText .= ' (' . $owner->name() . ')';
} else {
    $authorText = $hyperlink($comment->email(), 'mailto:' . $comment->email());
    if ($comment->name()) {
        $authorText .= ' (' . $comment->name() . ')';
    }
}
if ($website = $comment->website()) {
    $authorText .= sprintf($translate('Website: %s'), $hyperlink($website, $website));
}
?>

<?php /*// The comment id is in comment-list or comments-thread. Comment-thread includes comment children.
<div id="comment-<?= $comment->id() ?>" class="comment" data-comment-id="<?= $comment->id() ?>">
*/ ?>

<div class="comment-author">
    <p class="comment-author-name"><?= $authorText ?></p>
    <?php if (empty($skipGravatar)): ?>
    <img loading="lazy" class="gravatar" src="'//www.gravatar.com/avatar/<?= hash('sha256', trim($comment->email())) ?>"/>
    <?php endif; ?>
</div>
<div class="comment-actions">
    <ul class="actions icons-only">
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'approve')): ?>
        <li><button type="button"
            class="toggle-property approved unapproved o-icon-<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
            data-url="<?= $escape($comment->url('toggle-approved')) ?>"
            data-status="<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
            aria-label="<?= $v = $escape($translate('Toggle approbation')) ?>"
            title="<?= $v ?>"></button></li>
        <?php endif; ?>
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'flag')
            || ($comment->isFlagged() && $userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'unflag'))):
        ?>
        <li><button type="button"
            class="toggle-property flagged unflagged o-icon-<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
            data-url="<?= $escape($comment->url('toggle-flagged')) ?>"
            data-status="<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
            aria-label="<?= $v = $escape($translate('Toggle flag')) ?>"
            title="<?= $v ?>"></button></li>
        <?php endif; ?>
        <?php if ($userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'set-spam')
            || $userIsAllowed(\Comment\Controller\Admin\CommentController::class, 'set-not-spam')):
        ?>
        <li><button type="button"
            class="toggle-property spam not-spam o-icon-<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
            data-url="<?= $escape($comment->url('toggle-spam')) ?>"
            data-status="<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
            aria-label="<?= $v = $escape($translate('Toggle spam')) ?>"
            title="<?= $v ?>"></button></li>
        <?php endif; ?>
        <?php if ($comment->userIsAllowed('edit')): ?>
        <li><button type="button"
            class="o-icon-edit"
            data-url="<?= $escape($comment->url('edit')) ?>"
            aria-label="<?= $v = $escape($translate('Edit')) ?>"
            title="<?= $v ?>"></button></li>
        <?php endif; ?>
        <?php if ($comment->userIsAllowed('delete')): ?>
        <li><button type="button"
            class="o-icon-delete sidebar-content"
            data-sidebar-selector="#sidebar-comment"
            data-sidebar-content-url="<?= $escape($comment->url('delete-confirm')) ?>"
            aria-label="<?= $v = $escape($translate('Delete')) ?>"
            title="<?= $v ?>"></button></li>
        <?php endif; ?>
    </ul>
</div>
<div class="comment-body<?php if ($comment->isDeleted()): ?> comment-deleted<?php endif; ?>">
    <?= $escape($comment->body()) ?>
</div>
<?php if ($comment->userIsAllowed('create')): ?>
<p class="comment-reply"><?= $escape($translate('Reply')) ?></p>
<?php endif; ?>
