<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 */

use Comment\Api\Adapter\CommentAdapter;

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$i18n = $plugins->get('i18n');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
$userIsAllowed = $plugins->get('userIsAllowed');

$this->headLink()
    ->appendStylesheet($assetUrl('css/common-dialog.css', 'Common'))
    ->appendStylesheet($assetUrl('css/comment.css', 'Comment'))
    ->appendStylesheet($assetUrl('css/comment-admin.css', 'Comment'));
$this->headScript()
    ->appendFile($assetUrl('js/common-dialog.js', 'Common'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/comment.js', 'Comment'), 'text/javascript', ['defer' => 'defer'])
    ->appendFile($assetUrl('js/comment-admin.js', 'Comment'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'comment comments browse');

$sortHeadings = [
    // [
    //     'label' => $translate('Resource'),
    //     'value' => 'resource_title',
    // ],
    [
        'label' => $translate('Commenter'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Commenter email'),
        'value' => 'email',
    ],
    [
        'label' => $translate('Resource'),
        'value' => 'resource_id',
    ],
    [
        'label' => $translate('Date commented'),
        'value' => 'created',
    ],
];

$batchEditRight = $userIsAllowed(CommentAdapter::class, 'batch-update')
    || $userIsAllowed(CommentAdapter::class, 'batch-delete');
$editRight = $userIsAllowed(CommentAdapter::class, 'update')
    || $userIsAllowed(CommentAdapter::class, 'delete');
?>

<?= $this->pageTitle('', 1, $translate('Comments')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <?php // echo $hyperlink($translate('Advanced search'), $url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']) ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<?php if ($comments): ?>
<div id="page-actions">
    <?php if ($userIsAllowed(CommentAdapter::class, 'batch-update')): ?>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escapeAttr($url(null, ['action' => 'batch-approve'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Approve')) ?>"
        data-status="approved"
        title="<?= $escapeAttr($translate('Approve')) ?>"><?= $escape($translate('Approve')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escapeAttr($url(null, ['action' => 'batch-unapprove'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Unapprove')) ?>"
        data-status="unapproved"
        title="<?= $escapeAttr($translate('Unapprove')) ?>"><?= $escape($translate('Unapprove')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escapeAttr($url(null, ['action' => 'batch-flag'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Flag')) ?>"
        data-status="flagged"
        title="<?= $escapeAttr($translate('Flag')) ?>"><?= $escape($translate('Flag')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escapeAttr($url(null, ['action' => 'batch-unflag'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Unflag')) ?>"
        data-status="unflagged"
        title="<?= $escapeAttr($translate('Unflag')) ?>"><?= $escape($translate('Unflag')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escapeAttr($url(null, ['action' => 'batch-set-spam'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Set spam')) ?>"
        data-status="spam"
        title="<?= $escapeAttr($translate('Set spam')) ?>"><?= $escape($translate('Set spam')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escapeAttr($url(null, ['action' => 'batch-set-not-spam'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Set not spam')) ?>"
        data-status="not-spam"
        title="<?= $escapeAttr($translate('Set not spam')) ?>"><?= $escape($translate('Set not spam')) ?></a>
    <?php endif; ?>
    <?php if ($userIsAllowed(CommentAdapter::class, 'batch-delete')): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?= $escapeAttr($url(null, ['action' => 'batch-delete-confirm'], true)) ?>"
        aria-label="<?= $escapeAttr($translate('Delete')) ?>"
        title="<?= $escapeAttr($translate('Delete')) ?>"><?= $escape($translate('Delete')) ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($comments)): ?>
<div class="no-resources">
    <p><?= $translate('There are no comments.') ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<table data-comment-url="<?= $url('admin/comment') ?>" class="tablesaw <?php if ($batchEditRight): echo 'batch-edit'; endif ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-tag">
                <?php if ($editRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?= $translate('Comment') ?>
            </th>
            <th><?= $translate('Resource') ?></th>
            <th><?= $translate('Commenter') ?></th>
            <th><?= $translate('Date commented') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($comments as $comment): ?>
        <?php
        $resource = $comment->resource();
        $owner = $comment->owner();
        ?>
        <tr class="comment" data-id="<?= $comment->id() ?>">
            <td>
                <?php if ($batchEditRight): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?= $comment->id() ?>">
                <?php endif; ?>
                <div class="comment-body">
                    <?= $escape(mb_substr($comment->body(), 0, 200)) ?>
                </div>
                <span class="is-public-or-not<?php if (!$comment->isApproved()): echo ' o-icon-private'; endif; ?>" aria-label="<?= $translate('Private') ?>"></span>
                <?php if (mb_strlen($comment->body()) > 200): echo '…'; endif; ?>
                <ul class="actions icons-only">
                <?php // TODO Use buttons instead of a. ?>
                <?php $editRightComment = $comment->userIsAllowed('update'); ?>
                    <?php if ($editRightComment): ?>
                    <li><a href="#"
                        class="toggle-property approved unapproved o-icon-<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
                        data-url="<?= $escapeAttr($comment->url('toggle-approved')) ?>"
                        data-status="<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
                        aria-label="<?= $v = $escape($translate('Toggle approbation')) ?>"
                        title="<?= $v ?>"></a></li>
                    <li><a href="#"
                        class="toggle-property flagged unflagged o-icon-<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
                        data-url="<?= $escapeAttr($comment->url('toggle-flagged')) ?>"
                        data-status="<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
                        aria-label="<?= $v = $escapeAttr($translate('Toggle flag')) ?>"
                        title="<?= $v ?>"></a></li>
                    <li><a href="#"
                        class="toggle-property spam not-spam o-icon-<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
                        data-url="<?= $escapeAttr($comment->url('toggle-spam')) ?>"
                        data-status="<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
                        aria-label="<?= $v = $escape($translate('Toggle spam')) ?>"
                        title="<?= $v ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($comment->userIsAllowed('edit')): ?>
                    <li><a href="#"
                        class="comment-edit o-icon-edit"
                        aria-label="<?= $v = $escape($translate('Edit')) ?>"
                        title="<?= $v ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($comment->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?= $escapeAttr($comment->url('delete-confirm')) ?>"
                        aria-label="<?= $v = $escape($translate('Delete')) ?>"
                        title="<?= $v ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?= $escapeAttr($comment->url('show-details')) ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?= $v = $escape($translate('Details')) ?>"
                        title="<?= $v ?>"></a></li>
                </ul>
            </td>
            <td>
                <?php if ($resource): ?>
                    <?php
                    $urlResource = $url(
                        'admin/id',
                        ['controller' => $resource->getControllerName(), 'id' => $resource->id()],
                        ['fragment' => 'comments']
                    );
                    echo $hyperlink($resource->displayTitle(), $urlResource);
                ?>
                <span class="resource-name <?= $resource->getControllerName() ?>" aria-label="<?= $translate($resource->getControllerName()) ?>"></span>
                <?php else: ?>
                    [<?= $translate('Removed') ?>]
                <span class="resource-name no-resource"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($owner): ?>
                <span class="comment-email"><?= $hyperlink($owner->email(), $url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])) ?></span>
                <span class="comment-name"><?= $owner->name() ?></span>
                <?php else: ?>
                <span class="comment-email comment-public"><?= $hyperlink($comment->email(), 'mailto:' . $comment->email()) ?></span>
                <span class="comment-name"><?= $comment->name() ?></span>
                <span class="o-icon-users" aria-label="<?= $translate('Public') ?>"></span>
                <?php endif; ?>
                <?php if ($website = $comment->website()): ?>
                <span class="comment-website"><?= $website ?></span>
                <?php endif; ?>
            </td>
            <td>
                <?= $escape(sprintf($translate('Created: %s'), $i18n->dateFormat($comment->created()))) ?>
                <?php if ($v = $comment->modified()): ?>
                <br/>
                <?= $escape(sprintf($translate('Modified: %s'), $i18n->dateFormat($v))) ?>
                <?php endif; ?>
                <?php if ($v = $comment->edited()): ?>
                <br/>
                <?= $escape(sprintf($translate('Edited: %s'), $i18n->dateFormat($v))) ?>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after') ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $v = $escapeAttr($translate('Close')) ?>"
        title="<?= $v ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
