<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 */

use Comment\Api\Adapter\CommentAdapter;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$url = $plugins->get('url');
$hyperlink = $plugins->get('hyperlink');
$assetUrl = $plugins->get('assetUrl');
$userIsAllowed = $plugins->get('userIsAllowed');
$i18n = $plugins->get('i18n');

$this->headLink()->appendStylesheet($assetUrl('css/comment-admin.css', 'Comment'));
$this->headScript()->appendFile($assetUrl('js/comment-admin.js', 'Comment'));
$this->htmlElement('body')->appendAttribute('class', 'comment comments browse');

$sortHeadings = [
    // [
    //     'label' => $translate('Resource'),
    //     'value' => 'resource_title',
    // ],
    [
        'label' => $translate('Commenter'),
        'value' => 'name',
    ],
    [
        'label' => $translate('Commenter email'),
        'value' => 'email',
    ],
    [
        'label' => $translate('Resource'),
        'value' => 'resource_id',
    ],
    [
        'label' => $translate('Date commented'),
        'value' => 'created',
    ],
];

$batchEditRight = $userIsAllowed(CommentAdapter::class, 'batch-update')
    || $userIsAllowed(CommentAdapter::class, 'batch-delete');
$editRight = $userIsAllowed(CommentAdapter::class, 'update')
    || $userIsAllowed(CommentAdapter::class, 'delete');
?>

<?= $this->pageTitle($translate('Comments')) ?>

<?= $this->searchFilters() ?>

 <div class="browse-controls">
    <?= $this->pagination() ?>
    <?php // echo $hyperlink($translate('Advanced search'), $url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']) ?>
    <?= $this->sortSelector($sortHeadings) ?>
</div>

<form method="post" id="batch-form" class="disable-unsaved-warning">

<?php if ($comments): ?>
<div id="page-actions">
    <?php if ($userIsAllowed(CommentAdapter::class, 'batch-update')): ?>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escape($url(null, ['action' => 'batch-approve'], true)) ?>"
        aria-label="<?= $escape($translate('Approve')) ?>"
        data-status="approved"
        title="<?= $escape($translate('Approve')) ?>"><?= $escape($translate('Approve')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escape($url(null, ['action' => 'batch-unapprove'], true)) ?>"
        aria-label="<?= $escape($translate('Unapprove')) ?>"
        data-status="unapproved"
        title="<?= $escape($translate('Unapprove')) ?>"><?= $escape($translate('Unapprove')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escape($url(null, ['action' => 'batch-flag'], true)) ?>"
        aria-label="<?= $escape($translate('Flag')) ?>"
        data-status="flagged"
        title="<?= $escape($translate('Flag')) ?>"><?= $escape($translate('Flag')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escape($url(null, ['action' => 'batch-unflag'], true)) ?>"
        aria-label="<?= $escape($translate('Unflag')) ?>"
        data-status="unflagged"
        title="<?= $escape($translate('Unflag')) ?>"><?= $escape($translate('Unflag')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escape($url(null, ['action' => 'batch-set-spam'], true)) ?>"
        aria-label="<?= $escape($translate('Set spam')) ?>"
        data-status="spam"
        title="<?= $escape($translate('Set spam')) ?>"><?= $escape($translate('Set spam')) ?></a>
    <a href="#"
        class="button batch-actions batch-property"
        data-batch-property-url="<?= $escape($url(null, ['action' => 'batch-set-not-spam'], true)) ?>"
        aria-label="<?= $escape($translate('Set not spam')) ?>"
        data-status="not-spam"
        title="<?= $escape($translate('Set not spam')) ?>"><?= $escape($translate('Set not spam')) ?></a>
    <?php endif; ?>
    <?php if ($userIsAllowed(CommentAdapter::class, 'batch-delete')): ?>
    <a href="#"
        class="button delete batch-actions sidebar-content"
        data-sidebar-content-url="<?= $escape($url(null, ['action' => 'batch-delete-confirm'], true)) ?>"
        aria-label="<?= $escape($translate('Delete')) ?>"
        title="<?= $escape($translate('Delete')) ?>"><?= $escape($translate('Delete')) ?></a>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if (empty($comments)): ?>
<div class="no-resources">
    <p><?= $translate('There are no comments.') ?></p>
</div>
<?php $this->trigger('view.browse.after'); ?>

<?php else: ?>
<table class="tablesaw <?php if ($batchEditRight): echo 'batch-edit'; endif ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th class="column-tag">
                <?php if ($editRight): ?>
                <input type="checkbox" class="select-all">
                <?php endif; ?>
                <?= $translate('Comment') ?>
            </th>
            <th><?= $translate('Resource') ?></th>
            <th><?= $translate('Commenter') ?></th>
            <th><?= $translate('Date commented') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($comments as $comment): ?>
        <?php
        $resource = $comment->resource();
        $owner = $comment->owner();
        ?>
        <tr class="comment">
            <td>
                <?php if ($batchEditRight): ?>
                    <input type="checkbox" name="resource_ids[]" value="<?= $comment->id() ?>">
                <?php endif; ?>
                <?= $escape(substr($comment->body(), 0, 200)) ?>
                <span class="is-public-or-not<?php if (!$comment->isApproved()): echo ' o-icon-private'; endif; ?>" aria-label="<?= $translate('Private') ?>"></span>
                <?php if (strlen($comment->body()) > 200): echo '…'; endif; ?>
                <ul class="actions">
                <?php $editRightComment = $comment->userIsAllowed('update'); ?>
                    <?php if ($editRightComment): ?>
                    <li><a href="#"
                        class="toggle-property approved unapproved o-icon-<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
                        data-toggle-url="<?= $escape($comment->url('toggle-approved')) ?>"
                        data-status="<?= $comment->isApproved() ? 'approved' : 'unapproved' ?>"
                        aria-label="<?= $escape($translate('Toggle approbation')) ?>"
                        title="<?= $escape($translate('Toggle approbation')) ?>"></a></li>
                    <li><a href="#"
                        class="toggle-property flagged unflagged o-icon-<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
                        data-toggle-url="<?= $escape($comment->url('toggle-flagged')) ?>"
                        data-status="<?= $comment->isFlagged() ? 'flagged' : 'unflagged' ?>"
                        aria-label="<?= $escape($translate('Toggle flag')) ?>"
                        title="<?= $escape($translate('Toggle flag')) ?>"></a></li>
                    <li><a href="#"
                        class="toggle-property spam not-spam o-icon-<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
                        data-toggle-url="<?= $escape($comment->url('toggle-spam')) ?>"
                        data-status="<?= $comment->isSpam() ? 'spam' : 'not-spam' ?>"
                        aria-label="<?= $escape($translate('Toggle spam')) ?>"
                        title="<?= $escape($translate('Toggle spam')) ?>"></a></li>
                    <?php endif; ?>
                    <?php if ($comment->userIsAllowed('delete')): ?>
                    <li><a href="#"
                        class="o-icon-delete sidebar-content"
                        data-sidebar-content-url="<?= $escape($comment->url('delete-confirm')) ?>"
                        aria-label="<?= $escape($translate('Delete')) ?>"
                        title="<?= $escape($translate('Delete')) ?>"></a></li>
                    <?php endif; ?>
                    <li><a href="#"
                        data-sidebar-content-url="<?= $escape($comment->url('show-details')) ?>"
                        class="o-icon-more sidebar-content"
                        aria-label="<?= $escape($translate('Details')) ?>"
                        title="<?= $escape($translate('Details')) ?>"></a></li>
                </ul>
            </td>
            <td>
                <?php if ($resource): ?>
                    <?php
                    $url = $url(
                        'admin/id',
                        ['controller' => $resource->getControllerName(), 'id' => $resource->id()],
                        ['fragment' => 'comments']
                    );
                    echo $hyperlink($resource->displayTitle(), $url);
                ?>
                <span class="resource-name <?= $resource->getControllerName() ?>" aria-label="<?= $translate($resource->getControllerName()) ?>"></span>
                <?php else: ?>
                    [<?= $translate('Removed') ?>]
                <span class="resource-name no-resource"></span>
                <?php endif; ?>
            </td>
            <td>
                <?php if ($owner): ?>
                <span class="comment-email"><?= $hyperlink($owner->email(), $url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])) ?></span>
                <span class="comment-name"><?= $owner->name() ?></span>
                <?php else: ?>
                <span class="comment-email comment-public"><?= $hyperlink($comment->email(), 'mailto:' . $comment->email()) ?></span>
                <span class="comment-name"><?= $comment->name() ?></span>
                <span class="o-icon-users" aria-label="<?= $translate('Public') ?>"></span>
                <?php endif; ?>
                <?php if ($website = $comment->website()): ?>
                <span class="comment-website"><?= $website ?></span>
                <?php endif; ?>
            </td>
            <td><?= $escape($i18n->dateFormat($comment->created())) ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after') ?>
<div class="browse-controls">
    <?= $this->pagination() ?>
</div>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escape($translate('Close')) ?>"
        title="<?= $escape($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('.sidebar').on('submit', '#batch-delete-confirm', function(e) {
    var confirmForm = $(this);
    if (confirmForm.hasClass('batch-delete-all')) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input:checked').each(function() {
            confirmForm.append($(this).clone().attr('type', 'hidden'));
        });
    }
});
</script>
<?php endif; ?>
